a = input("Say something: ")

print("Qual tipo do valor?")
print(type(a))
print('Ele é uma letra?')
print(a.isalpha())
print('Ele é um numero?')
print(a.isnumeric())
print('Ele ta em caixa alta?')
print(a.isupper())
print('Ele ta em caixa baixa?')
print(a.islower())
print('Só tem espacos?')
print(a.isspace())
print('Esta capitalizado?')
print(a.istitle())